name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > key.jks
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.KEYSTORE_ALIAS }}" >> keystore.properties
          echo "storeFile=key.jks" >> keystore.properties

      - name: Get version code
        run: echo "VERSION_CODE=$(git rev-list --first-parent --count HEAD)" >> $GITHUB_ENV

      - name: Build release APK
        run: ./gradlew assembleStableRelease -s
        env:
          VERSION_NAME: ${{ github.ref_name }}
          VERSION_CODE: ${{ env.VERSION_CODE }}

      - name: Rename APK
        run: |
          mv build/outputs/apk/stable/release/latinime-stable-release.apk \
             ./keyboard-${{ github.ref_name }}.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Keyboard ${{ github.ref_name }}
          files: ./keyboard-${{ github.ref_name }}.apk
          draft: true
          generate_release_notes: true
